branches:
  only:
    - main

sudo: required
services:
  - docker



before_install:
  - docker build -t elijah/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true elijah/docker-react npm run test
