sudo: required
language: generic

# branches:
#   only:
#     - main

services:
  - docker



before_install:
  - docker build -t elijah/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true elijah/docker-react npm run test


deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Docker-Toy"
  env: "Docker-Toy-env"
  bucket_name: "elasticbeanstalk-us-east-2-043357425302"
  bucket_path: "Docker-Toy"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"

  